site_name: hhzs's wiki
theme:
  name: material
  logo: image/pig.png # logo å›¾ç‰‡
  favicon: image/pig.png # ç½‘ç«™å›¾æ ‡
  language: zh
  features: # åŠŸèƒ½  
    - content.code.copy # å¤åˆ¶ä»£ç æŒ‰é’®
    - content.code.annotate #ä»£ç ä¸­æ³¨é‡Š
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    annotation: material/bell-circle  #ä¸admontionå¹³çº§

# ä»£ç ä»“åº“ä¿¡æ¯
repo_name: hhzs1024/knob_soft_LCD # ä»“åº“åç§°
repo_url: https://github.com/hhzs1024/knob_soft_LCD.git # ä»“åº“åœ°å€
# ç‰ˆæƒä¿¡æ¯
copyright: Copyright &copy; 2025 ~ now | ğŸš€ hhzs

# é¢å¤–é…ç½®é¡¹
extra:
  generator: false # æ˜¯å¦æ˜¾ç¤ºç”Ÿæˆå™¨
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hhzs1024/

# æ‰©å±•
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition            #è­¦å‘Š
  - pymdownx.details      #ç»†èŠ‚
  - pymdownx.superfences  #è¶…çº§å›´æ  ä»¥ä¸Šä¸‰ä¸ªä½œæ–‡å­—æ¡†æ˜¾ç¤º
  - attr_list
  - md_in_html

use_directory_urls: false

nav:
    - é¦–é¡µ: index.md
    - åµŒå…¥å¼:
      - ç”µè·¯: embedded.md
    - mkdocs: 
      - mkdocsä½¿ç”¨: ./mkdocs/mkdocs.md
      - markdownè¯­æ³•: ./mkdocs/markdown.md
    - cortexM3:
      - æ¦‚è§ˆ: ./mkdocs/cortexM3/cortexM3.md
    - assembly:
      - æ±‡ç¼–å®ä¾‹: ./mkdocs/assembly/assembly.md
    - å…³äº: about.md
